{% set name = "specclassify" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/specclassify-{{ version }}.tar.gz
  sha256: 740456cf023365849d70898264f63028d0f087130ebd9491201820638721f8e5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - geoarray >=0.15.0
    - matplotlib-base
    - numpy
    - py-tools-ds >=0.18.0
    - python >={{ python_min }}
    - scikit-learn
    - tqdm

test:
  imports:
    - specclassify
    - specclassify.classifiers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/geomultisens/specclassify
  summary: A Python package for multi- or hyperspectral image classification.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
