{% set name = "specclassify" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/specclassify-{{ version }}.tar.gz
  sha256: b142283042f1c6b56ca8132658f87917dc345d476e247a809ae8745b7e1fae5a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - geoarray >=0.15.0
    - matplotlib-base
    - numpy
    - py-tools-ds >=0.18.0
    - python >=3.6
    - scikit-learn
    - tqdm

test:
  imports:
    - specclassify
    - specclassify.classifiers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/geomultisens/specclassify
  summary: A Python package for multi- or hyperspectral image classification.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
