{% set name = "specclassify" %}
{% set version = "0.2.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/specclassify-{{ version }}.tar.gz
  sha256: e931d31cd36ebf7377025a71d71ceecbf08653b52ee9725d273d2b33db4b0764

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - geoarray >=0.8.0
    - matplotlib-base
    - numpy
    - py-tools-ds >=0.12.4
    - python
    - scikit-learn
    - tqdm

test:
  imports:
    - specclassify
    - specclassify.classifiers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitext.gfz-potsdam.de/geomultisens/specclassify
  summary: A Python package for multi- or hyperspectral image classification.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
